image:
  repository: realartisan/statera
  tag: v1.0.1
  pullPolicy: IfNotPresent

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "200m"
    memory: "256Mi"

serviceAccount:
  create: true
  name: statera

cronjob:
  enabled: true
  schedule: "*/5 * * * *"  # Every 5 minutes
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  resources:
    limits:
      cpu: "500m"
      memory: "128Mi"
    requests:
      cpu: "200m"
      memory: "64Mi"

daemonset:
  enabled: false


