image:
  repository: realartisan/statera
  tag: v1.0.0
  pullPolicy: IfNotPresent

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "200m"
    memory: "256Mi"

serviceAccount:
  create: true
  name: statera
