apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: statera
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: statera
  template:
    metadata:
      labels:
        app: statera
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
      - name: statera
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}
